import { useState } from 'react';
import type { BudgetSettings } from '../../../shared/budget-workspace';
import { formatMoney } from '../../format';

export function BudgetConfiguration({ settings, busy, onSave }: { settings: BudgetSettings; busy: boolean; onSave(value: BudgetSettings): Promise<void> }) {
  const [draft, setDraft] = useState(() => structuredClone(settings));
  const allocated = draft.categories.filter((item) => item.active && item.includedInOverallBudget).reduce((sum, item) => sum + Number(item.monthlyAmount || 0), 0);
  const meal = draft.categories.filter((item) => item.active && item.group === 'meal').reduce((sum, item) => sum + Number(item.monthlyAmount || 0), 0);
  function updateCategory(index: number, field: 'name' | 'monthlyAmount' | 'schedule', value: string) { setDraft((current) => ({ ...current, categories: current.categories.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) })); }
  function addCategory() { setDraft((current) => ({ ...current, categories: [...current.categories, { id: `category-${crypto.randomUUID()}`, name: 'New category', group: 'other', monthlyAmount: '0.00', includedInOverallBudget: true, schedule: 'unassigned', weekdays: [], active: true }] })); }
  return <section className="budget-configuration" aria-labelledby="budget-configuration-heading"><div className="section-heading"><div><p className="eyebrow">Editable plan</p><h2 id="budget-configuration-heading">Budget configuration</h2></div><strong>₹{formatMoney(allocated.toFixed(2))} allocated</strong></div>
    <div className="budget-config-summary"><label>Monthly overall limit<input inputMode="decimal" value={draft.overallMonthlyLimit} onChange={(event) => setDraft({ ...draft, overallMonthlyLimit: event.target.value })} /></label><label>Weekly food target<input inputMode="decimal" value={draft.weeklyFoodTarget} onChange={(event) => setDraft({ ...draft, weeklyFoodTarget: event.target.value })} /></label></div>
    {Number(draft.weeklyFoodTarget) * 4 !== meal && <p className="budget-warning">The weekly food target × 4 does not match the monthly meal allocation of ₹{formatMoney(meal.toFixed(2))}. Both remain independent.</p>}
    <div className="budget-category-editor">{draft.categories.filter((item) => item.active).map((item) => { const index = draft.categories.findIndex((value) => value.id === item.id); return <div key={item.id}><input aria-label={`${item.name} name`} value={item.name} onChange={(event) => updateCategory(index, 'name', event.target.value)} /><input aria-label={`${item.name} monthly budget`} inputMode="decimal" value={item.monthlyAmount} onChange={(event) => updateCategory(index, 'monthlyAmount', event.target.value)} /><select aria-label={`${item.name} allocation schedule`} value={item.schedule} onChange={(event) => updateCategory(index, 'schedule', event.target.value)}><option value="unassigned">Unassigned</option><option value="daily">Daily</option><option value="weekdays">Selected weekdays</option><option value="monthly">Monthly</option></select>{item.schedule === 'weekdays' && <fieldset className="budget-weekdays"><legend>Scheduled weekdays</legend>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((label, weekdayIndex) => <label key={label}><input type="checkbox" checked={item.weekdays.includes(weekdayIndex + 1)} onChange={(event) => setDraft((current) => ({ ...current, categories: current.categories.map((value, itemIndex) => itemIndex === index ? { ...value, weekdays: event.target.checked ? [...value.weekdays, weekdayIndex + 1].sort() : value.weekdays.filter((day) => day !== weekdayIndex + 1) } : value) }))} />{label}</label>)}</fieldset>}<label><input type="checkbox" checked={item.includedInOverallBudget} onChange={(event) => setDraft((current) => ({ ...current, categories: current.categories.map((value, itemIndex) => itemIndex === index ? { ...value, includedInOverallBudget: event.target.checked } : value) }))} />Included</label><button type="button" className="text-button danger-action" onClick={() => setDraft((current) => ({ ...current, categories: current.categories.map((value, itemIndex) => itemIndex === index ? { ...value, active: false } : value) }))}>Remove</button></div>; })}</div>
    <div className="budget-config-actions"><button type="button" className="secondary-button" onClick={addCategory}>Add category</button><button type="button" className="primary-button" disabled={busy} onClick={() => void onSave(draft).catch(() => undefined)}>Save configuration</button></div>
  </section>;
}
